---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
platforms:
  - name: awx-patching-default-xenial
    source:
      alias: ubuntu/xenial/amd64
  - name: awx-patching-default-bionic
    source:
      type: image
      alias: ubuntu/bionic/amd64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: lxd
verifier:
  name: testinfra
  lint:
    name: flake8