---
- name: Ensure redis socket directory exists
  file: path=/var/run/redis state=directory mode=0750 owner=redis group=redis

- name: Ensure Redis socket directory has the correct SELinux context
  shell: restorecon -R /var/run/redis

- name: Create tmpfiles.d entry for redis socket directory
  template:
    src: redis_tmpd.conf
    dest: /etc/tmpfiles.d/redis.conf
    force: yes
    mode: '0640'
    owner: root
    group: root
    
- name: add awx to the redis group so it can access the socket
  user: name=awx groups=redis append=yes

- name: Create redis.conf
  template:
    src: redis.conf.j2
    dest: /etc/redis.conf
    owner: redis
    group: root
    mode: '0640'
  notify: Restart redis.

